"""
F1+F2 — OpenFOAM 케이스 디렉터리 생성 (blockMesh 배경격자 + snappyHexMesh)

1차 스코프: tutorial 급 형상만.
  · 벤드 없음 + 덕트 밀폐(sealed) + 관이 덕트 z 범위와 일치
  → 배경격자 = air_bbox, blockMesh 6면에 patch 이름을 직접 부여
    (Fluent 의 케이싱이 하던 일을 blockMesh 가 공짜로 해줌)
probe(벤드가 덕트 밖으로 나감)는 배경을 global_bbox 로 잡고 공기 외곽을
snappy 가 만들게 해야 하므로 별도 단계에서 확장함.

관벽 처리: Phase 2 는 A-lite — solid_tube 를 cellZone 으로 실제 메시.
  snappy 에는 Fluent 의 thin-volume 이 없어 관벽(t=0.65mm)에 셀을 넣으려면
  표면 level 을 t 미만 크기까지 올려야 함. 셀 증가를 감수하고 위상 검증을
  우선함. B안(baffle+thermalBaffle, 관벽 제거)은 Phase 3 에서 결정.

사이징: meshing.sizing() 의 값만 사용. 사람이 만질 값 없음.
  배경 h_bg = 2·h_air (Fluent 상·하류와 동일)
  level 1 = h_air (코어), level L_ref ≈ h_ref, level L_wall < t_wall
"""
from __future__ import annotations

import math
import shutil
from pathlib import Path

from fthx.params import FTHXParams
from fthx import meshing as MSH
from foam.foam_stl import export_stl


def _scale_stl(src: Path, dst: Path, f: float = 0.001) -> None:
    """binary STL 좌표 스케일 (mm→m). blockMesh 는 convertToMeters 로
    변환되지만 triSurface·eMesh·locationInMesh 는 변환되지 않으므로
    케이스에 들어가는 STL 은 m 단위여야 함 (실측: locationInMesh 단위
    불일치로 FATAL — 'Point ... is not inside the mesh')."""
    import numpy as np
    b = bytearray(src.read_bytes())
    n = int.from_bytes(b[80:84], "little")
    arr = np.frombuffer(b, dtype="<f4", count=n * 12 + 0, offset=84).copy() if False else None
    # 레코드 50B = 법선3f + 정점9f + attr2B → f4 view 는 불가(50 이 4의 배수 아님)
    import struct
    for i in range(n):
        off = 84 + i * 50
        vals = struct.unpack_from("<12f", b, off)
        struct.pack_into("<12f", b, off, *(v * f for v in vals))
    dst.write_bytes(bytes(b))

FOAM_HEADER = """\
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      {obj};
}}
// generated by fthx.openfoam — 수정하지 말 것 (params 에서 재생성됨)
"""


def _hdr(obj: str) -> str:
    return FOAM_HEADER.format(obj=obj)


def _level_for(h_bg: float, target: float, slack: float = 1.0) -> int:
    """배경 h_bg 에서 target·slack 이하가 되는 최소 refinement level.
    slack>1 이면 목표보다 약간 굵은 level 을 허용 (한 단계 아래로 과세분 방지)."""
    lv = 0
    h = h_bg
    while h > target * slack * (1 + 1e-9):
        lv += 1
        h /= 2.0
    return lv


def plan(p: FTHXParams) -> dict:
    """사이징 → snappy level 계획. 게이트/검산에 쓰는 수치를 한곳에 모음."""
    s = MSH.sizing(p)
    t = p.tube
    h_bg = 2.0 * s["h_air_mm"]
    t_wall = (t.Do - t.Di) / 2.0
    lv_core = _level_for(h_bg, s["h_air_mm"])                 # 보통 1
    lv_ref = _level_for(h_bg, s["h_ref_mm"], slack=1.2)       # 보통 2 (0.794≈h_ref)
    lv_wall = _level_for(h_bg, 0.75 * t_wall)                 # 벽에 셀이 들어가는 크기
    return {"sizing": s, "h_bg_mm": h_bg, "t_wall_mm": t_wall,
            "lv_core": lv_core, "lv_ref": lv_ref, "lv_wall": lv_wall,
            "h_at": {f"level{l}": h_bg / 2 ** l
                     for l in range(max(lv_wall, lv_ref) + 1)}}


def _block_mesh_dict(p: FTHXParams, pl: dict) -> str:
    d, dk = p.domain, p.duct_box
    x0, x1 = p.core_bbox[0], p.core_bbox[1]
    xa, xb = x0 - d.L_up, x1 + d.L_down
    ya, yb, za, zb = dk["y0"], dk["y1"], dk["z0"], dk["z1"]
    h = pl["h_bg_mm"]
    n = [max(1, round((b - a) / h)) for a, b in ((xa, xb), (ya, yb), (za, zb))]
    v = [(xa, ya, za), (xb, ya, za), (xb, yb, za), (xa, yb, za),
         (xa, ya, zb), (xb, ya, zb), (xb, yb, zb), (xa, yb, zb)]
    verts = "\n".join(f"    ({a} {b} {c})" for a, b, c in v)
    return _hdr("blockMeshDict") + f"""
convertToMeters 0.001;      // 형상 단위 = mm

vertices
(
{verts}
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({n[0]} {n[1]} {n[2]}) simpleGrading (1 1 1)
);

boundary
(
    air_inlet  {{ type patch; faces ((0 4 7 3)); }}
    air_outlet {{ type patch; faces ((1 2 6 5)); }}
    duct_wall  {{ type wall;  faces ((0 1 5 4) (3 7 6 2)
                                     (0 3 2 1) (4 5 6 7)); }}
);
"""


def _feature_dict(stl_names: list[str]) -> str:
    body = ""
    for n in stl_names:
        body += f"""
{n}.stl
{{
    extractionMethod    extractFromSurface;
    includedAngle       150;
    writeObj            no;
}}
"""
    return _hdr("surfaceFeatureExtractDict") + body


def _snappy_dict(p: FTHXParams, pl: dict, entries: dict[str, dict]) -> str:
    """entries: {stl이름: {"level": int, "zone": bool}}.
    zone=True → cellZone(내부 유지), zone=False → 경계면(내부 셀 제거, wall patch)"""
    d, dk = p.domain, p.duct_box
    x0 = p.core_bbox[0]
    loc = tuple(v / 1000.0 for v in (         # [m] — STL·메시와 단위 일치
        (x0 - d.L_up + x0) / 2 + 0.0123,
        (dk["y0"] + dk["y1"]) / 2 + 0.0231,
        (dk["z0"] + dk["z1"]) / 2 + 0.0312))
    geom, feat, surf = "", "", ""
    for name, e in entries.items():
        lv = e["level"]
        geom += f'    {name}.stl {{ type triSurfaceMesh; name {name}; }}\n'
        feat += f'    {{ file "{name}.eMesh"; level {lv}; }}\n'
        if e["zone"]:
            surf += (f"        {name}\n        {{\n"
                     f"            level ({lv} {lv});\n"
                     f"            faceZone {name};\n"
                     f"            cellZone {name};\n"
                     f"            cellZoneInside inside;\n        }}\n")
        else:
            surf += (f"        {name}\n        {{\n"
                     f"            level ({lv} {lv});\n"
                     f"            patchInfo {{ type wall; }}\n        }}\n")
    core = next(n for n in entries if n.startswith("fluid_air_core"))
    return _hdr("snappyHexMeshDict") + f"""
castellatedMesh true;
snap            true;
addLayers       false;      // y+ 벽함수 범위 실측(190/131) — 프리즘 불필요

geometry
{{
{geom}}}

castellatedMeshControls
{{
    maxLocalCells       2000000;
    maxGlobalCells      8000000;
    minRefinementCells  0;
    nCellsBetweenLevels 2;
    resolveFeatureAngle 30;

    features
    (
{feat}    );

    refinementSurfaces
    {{
{surf}    }}

    refinementRegions
    {{
        {core} {{ mode inside; levels ((1e15 {pl['lv_core']})); }}
    }}

    locationInMesh ({loc[0]} {loc[1]} {loc[2]});   // 상류 공기 내부 [m]
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch            3;
    tolerance               2.0;
    nSolveIter              50;
    nRelaxIter              5;
    nFeatureSnapIter        10;
    implicitFeatureSnap     false;
    explicitFeatureSnap     true;
    multiRegionFeatureSnap  true;   // cellZone 계면에서도 feature 스냅
}}

addLayersControls
{{
    relativeSizes true;
    layers {{ }}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.25;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 5;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}

meshQualityControls
{{
    #includeEtc "caseDicts/meshQualityDict"
    minTetQuality   1e-15;
    nSmoothScale    4;
    errorReduction  0.75;
}}

writeFlags ();
mergeTolerance 1e-6;
"""


_MINI = {
    "controlDict": """
application     snappyHexMesh;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         1;
deltaT          1;
writeControl    timeStep;
writeInterval   1;
""",
    "fvSchemes": """
ddtSchemes {}
gradSchemes {}
divSchemes {}
laplacianSchemes {}
interpolationSchemes {}
snGradSchemes {}
""",
    "fvSolution": """
solvers {}
""",
}

_ALLRUN = r"""\
#!/usr/bin/env bash
# 메시 생성 + 진단 (한 번 실행으로 여러 검산을 같이 수행)
cd "$(dirname "$0")"
# OpenFOAM 환경 자동 탐지 (미리 source 안 해도 동작)
if ! command -v blockMesh >/dev/null 2>&1; then
    for rc in /usr/lib/openfoam/openfoam*/etc/bashrc; do
        [ -f "$rc" ] && source "$rc" && break
    done
fi
command -v blockMesh >/dev/null 2>&1 || { echo "OpenFOAM 을 찾을 수 없음"; exit 2; }
set -e
run() { echo ">>> $1"; "$@" > "log.$1" 2>&1 || { echo "<<< $1 실패 — log.$1"; exit 1; }; echo "<<< $1 OK"; }

run surfaceFeatureExtract
run blockMesh
run snappyHexMesh -overwrite
run checkMesh -constant

echo "──────── 요약 ────────"
grep -E "^Snapped mesh" log.snappyHexMesh | tail -1 || true
echo "── cellZones (이름: 셀 수) — 0 이 있으면 존 형성 실패"
awk '/^\(?[A-Za-z_]/{z=$1; sub(/^\(/,"",z)} /List<label>/{getline n; print "  " z ": " n}' constant/polyMesh/cellZones
grep -E "Mesh OK|Failed .* mesh checks" log.checkMesh
"""


def write_case(p: FTHXParams, case_dir: str, force: bool = False,
               mode: str = "air") -> dict:
    """tutorial 급 형상의 snappy 케이스 생성. 반환: plan + 파일 목록.

    mode="air": 공기측 단일 region — fluid_ref 제외, 관 표면=wall patch.
               물리 설정(0/, constant/, fvOptions, Allrun.solve)까지 생성.
    mode="cht": 전 바디 cellZone (A-lite) — 메시만. conjugate 는 Phase 3 후반.
    """
    d = p.domain
    if d.include_bends:
        raise NotImplementedError(
            "벤드 포함 형상(probe)은 배경격자를 global_bbox 로 잡는 확장이 "
            "필요함 — Phase 5. 지금은 tutorial 급만 지원.")
    if not p.duct.sealed:
        raise NotImplementedError("덕트 간극(바이패스) 형상은 미지원 — Phase 5.")

    case = Path(case_dir)
    if case.exists() and force:
        shutil.rmtree(case)
    (case / "system").mkdir(parents=True, exist_ok=True)
    (case / "constant" / "triSurface").mkdir(parents=True, exist_ok=True)
    (case / "0").mkdir(exist_ok=True)

    # STL 은 여기서 직접 생성 (F0 내장 검증 포함) → triSurface 로 복사
    meta = export_stl(p, outdir=str(case / "_stl_tmp"))
    stl_names = []
    for b in meta["bodies"].values():
        src = case / "_stl_tmp" / b["file"]
        _scale_stl(src, case / "constant" / "triSurface" / b["file"])
        stl_names.append(b["file"][:-4])
    shutil.rmtree(case / "_stl_tmp")

    pl = plan(p)
    entries: dict[str, dict] = {}
    drop: list[str] = []
    for n in sorted(stl_names):
        if n.startswith("fluid_air_core"):
            entries[n] = {"level": pl["lv_core"], "zone": True}
        elif n.startswith("solid_tube"):
            if mode == "cht":       # A-lite: 관벽을 실제 셀존으로
                entries[n] = {"level": pl["lv_wall"], "zone": True}
            else:                   # air: 관 표면 = wall patch, 내부 셀 제거
                entries[n] = {"level": pl["lv_ref"], "zone": False}
        elif n.startswith("fluid_ref"):
            if mode == "cht":
                entries[n] = {"level": pl["lv_ref"], "zone": True}
            else:
                drop.append(n)      # 공기측 해석에는 냉매 도메인 불필요
        elif n.startswith("fluid_air_"):
            drop.append(n)          # 상·하류는 배경 그대로 (공기 연속체)
        else:
            entries[n] = {"level": pl["lv_ref"], "zone": mode == "cht"}

    (case / "system" / "blockMeshDict").write_text(
        _block_mesh_dict(p, pl), encoding="utf-8", newline="\n")
    (case / "system" / "snappyHexMeshDict").write_text(
        _snappy_dict(p, pl, entries), encoding="utf-8", newline="\n")
    (case / "system" / "surfaceFeatureExtractDict").write_text(
        _feature_dict(sorted(entries)), encoding="utf-8", newline="\n")
    for name, body in _MINI.items():
        (case / "system" / name).write_text(_hdr(name) + body, encoding="utf-8", newline="\n")
    ar = case / "Allrun.mesh"
    ar.write_text(_ALLRUN, encoding="utf-8", newline="\n")
    ar.chmod(0o755)

    # 사용하지 않는 STL 은 triSurface 에서 제거 (혼동 방지)
    for n in drop:
        (case / "constant" / "triSurface" / f"{n}.stl").unlink()

    pl["zones"] = {n: e["level"] for n, e in entries.items() if e["zone"]}
    pl["surfaces"] = {n: e["level"] for n, e in entries.items() if not e["zone"]}
    pl["mode"] = mode
    if mode == "air":
        pl["physics"] = write_physics(p, case)
    pl["case_dir"] = str(case)
    pl["gate"] = {
        "fluent_ref_cells": 68641,
        "rule": "셀 수가 Fluent tutorial 과 같은 자릿수(<10배)면 통과. "
                "관벽 level 상향(A-lite)으로 증가는 예상된 것",
    }
    return pl


# ══════════════════════════════════════════════════════════════════
#  F3 — 물리 설정 (공기측 단일 region · simpleFoam · 포러스 fvOptions)
# ══════════════════════════════════════════════════════════════════
def porous_df(p: FTHXParams) -> dict:
    """closure.air_side() 의 Fluent 형 계수를 OpenFOAM DarcyForchheimer 로.

    Fluent:   dp/L = (mu/alpha)·u + C2·(rho/2)·u²   (superficial u)
    OpenFOAM: dp/L =  mu·d·u     + f·(rho/2)·u²
    →  d = 1/alpha [1/m²],  f = C2 [1/m]   (직접 대응, 변환계수 없음)

    핀은 z(적층 방향) 유동을 막음 → 횡방향 z 는 ×1e3 저항 (관행값).
    y 는 핀 채널 안에서 자유 → x 와 동일로 근사.
    """
    from fthx import closure
    a = closure.air_side(p)
    od = p.operating_derived()["air"]
    # ⚠ closure 의 alpha 와 C2 는 각각 '단독으로' dp 전체를 재현하는
    #   상호배타적 폐합임 (mu·(1/alpha)·u·W ≡ dp, C2·W·(rho/2)u² ≡ dp).
    #   둘을 합치면 구조적으로 2배 — 설계점(Re~2e3, 관성 지배)은 f=C2 단독.
    #   실측: d+f 동시 적용 시 CFD dP 16.0 Pa (해석해 4.16 의 ~4배).
    #   저유량 스윕에서는 Re 별 재폐합 필요 (closure 규약 이슈로 기록).
    return {"d": 0.0, "f": a["C2_1perm"], "block_factor": 1e3,
            "dp_core_Pa": a["dp_core_Pa"], "porosity": a["porosity"],
            "rho": od["rho"], "mu": od["mu"], "nu": od["mu"] / od["rho"],
            "U_face": p.operating.air.V_face}


def write_physics(p: FTHXParams, case: Path) -> dict:
    """0/ · constant/ · fvOptions · 솔버용 system · Allrun.solve 생성."""
    pf = porous_df(p)
    U, nu, rho = pf["U_face"], pf["nu"], pf["rho"]
    dk = p.duct_box
    H = (dk["y1"] - dk["y0"]) / 1000.0                # 덕트 높이 [m]
    I, L = 0.05, 0.1 * H                              # 난류강도 5%, 길이척도 0.1H
    k_in = 1.5 * (I * U) ** 2
    eps_in = 0.09 ** 0.75 * k_in ** 1.5 / L
    core = f"fluid_air_core_r{1:02d}"                 # tutorial: r01 하나

    def w(rel: str, body: str, obj: str | None = None):
        f = case / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        hdr = _hdr(obj or f.name)
        f.write_text(hdr + body, encoding="utf-8", newline="\n")

    wall_re = '"(duct_wall|solid_tube.*)"'
    w("0/U", f"""
dimensions [0 1 -1 0 0 0 0];
internalField uniform ({U} 0 0);
boundaryField
{{
    air_inlet  {{ type fixedValue; value uniform ({U} 0 0); }}
    air_outlet {{ type zeroGradient; }}
    {wall_re}  {{ type noSlip; }}
}}
""")
    w("0/p", """
dimensions [0 2 -2 0 0 0 0];
internalField uniform 0;
boundaryField
{
    air_inlet  { type zeroGradient; }
    air_outlet { type fixedValue; value uniform 0; }
    """ + wall_re + """ { type zeroGradient; }
}
""")
    w("0/k", f"""
dimensions [0 2 -2 0 0 0 0];
internalField uniform {k_in:.6g};
boundaryField
{{
    air_inlet  {{ type fixedValue; value uniform {k_in:.6g}; }}
    air_outlet {{ type zeroGradient; }}
    {wall_re}  {{ type kqRWallFunction; value uniform {k_in:.6g}; }}
}}
""")
    w("0/epsilon", f"""
dimensions [0 2 -3 0 0 0 0];
internalField uniform {eps_in:.6g};
boundaryField
{{
    air_inlet  {{ type fixedValue; value uniform {eps_in:.6g}; }}
    air_outlet {{ type zeroGradient; }}
    {wall_re}  {{ type epsilonWallFunction; value uniform {eps_in:.6g}; }}
}}
""")
    w("0/nut", f"""
dimensions [0 2 -1 0 0 0 0];
internalField uniform 0;
boundaryField
{{
    air_inlet  {{ type calculated; value uniform 0; }}
    air_outlet {{ type calculated; value uniform 0; }}
    {wall_re}  {{ type nutkWallFunction; value uniform 0; }}
}}
""")
    w("constant/transportProperties",
      f"\ntransportModel Newtonian;\nnu {nu:.6e};\n")
    w("constant/turbulenceProperties", """
simulationType RAS;
RAS { RASModel kEpsilon; turbulence on; printCoeffs off; }
""")
    w("system/fvOptions", f"""
porousCore
{{
    type            explicitPorositySource;
    active          yes;
    explicitPorositySourceCoeffs
    {{
        selectionMode   cellZone;
        cellZone        {core};
        type            DarcyForchheimer;
        d   ({pf['d']:.6e} {pf['d']:.6e} {pf['d'] * pf['block_factor']:.6e});
        f   ({pf['f']:.6f} {pf['f']:.6f} {pf['f'] * pf['block_factor']:.6f});
        coordinateSystem
        {{
            origin (0 0 0);
            rotation {{ type axesRotation; e1 (1 0 0); e2 (0 1 0); }}
        }}
    }}
}}
""")
    w("system/fvSchemes", """
ddtSchemes      { default steadyState; }
gradSchemes     { default cellLimited Gauss linear 1; }
divSchemes
{
    default                     none;
    div(phi,U)                  bounded Gauss linearUpwind grad(U);
    div(phi,k)                  bounded Gauss upwind;
    div(phi,epsilon)            bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear limited corrected 0.33; }
interpolationSchemes { default linear; }
snGradSchemes   { default limited corrected 0.33; }
wallDist        { method meshWave; }
""", obj="fvSchemes")
    w("system/fvSolution", """
solvers
{
    p       { solver GAMG; smoother GaussSeidel; tolerance 1e-7; relTol 0.01; }
    "(U|k|epsilon)" { solver smoothSolver; smoother symGaussSeidel;
                      tolerance 1e-8; relTol 0.1; }
}
SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent no;
    residualControl { p 1e-4; U 1e-5; "(k|epsilon)" 1e-5; }
}
relaxationFactors
{
    fields    { p 0.3; }
    equations { U 0.7; "(k|epsilon)" 0.7; }
}
""", obj="fvSolution")
    w("system/controlDict", """
application     simpleFoam;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         2000;
deltaT          1;
writeControl    timeStep;
writeInterval   500;
purgeWrite      2;
functions
{
    pIn
    {
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            air_inlet;
        operation       areaAverage;
        fields          (p);
        writeFields     no;
        writeControl    timeStep;
        writeInterval   20;
        log             no;
    }
    pOut
    {
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            air_outlet;
        operation       areaAverage;
        fields          (p);
        writeFields     no;
        writeControl    timeStep;
        writeInterval   20;
        log             no;
    }
}
""", obj="controlDict")
    w("system/decomposeParDict", """
numberOfSubdomains 8;
method scotch;
""")
    allrun = r"""#!/usr/bin/env bash
# 솔버 실행 + ΔP 추출.  코어 수: FTHX_NP (기본 8, nproc 상한)
cd "$(dirname "$0")"
if ! command -v simpleFoam >/dev/null 2>&1; then
    for rc in /usr/lib/openfoam/openfoam*/etc/bashrc; do
        [ -f "$rc" ] && source "$rc" && break
    done
fi
set -e
run() { echo ">>> $1"; "${@}" > "log.$1" 2>&1 || { echo "<<< $1 실패 — log.$1"; exit 1; }; echo "<<< $1 OK"; }

NP=${FTHX_NP:-8}
AVAIL=$(nproc)
[ "$NP" -gt "$AVAIL" ] && NP=$AVAIL
if [ "$NP" -gt 1 ] && command -v mpirun >/dev/null 2>&1; then
    sed -i "s/^numberOfSubdomains.*/numberOfSubdomains $NP;/" system/decomposeParDict
    run decomposePar -force
    echo ">>> simpleFoam (${NP}코어)"
    mpirun -np "$NP" simpleFoam -parallel > log.simpleFoam 2>&1 \
        || { echo "<<< simpleFoam 실패 — log.simpleFoam"; exit 1; }
    echo "<<< simpleFoam OK"
    run reconstructPar -latestTime
else
    echo ">>> simpleFoam (직렬)"
    simpleFoam > log.simpleFoam 2>&1 \
        || { echo "<<< simpleFoam 실패 — log.simpleFoam"; exit 1; }
    echo "<<< simpleFoam OK"
fi

# 재시작하면 postProcessing/<fn>/<시작시각>/ 이 여럿 생김 — 최신 것을 읽음
latest() { ls "postProcessing/$1" | sort -n | tail -1; }
PIN=$(tail -1 "postProcessing/pIn/$(latest pIn)/surfaceFieldValue.dat" | awk '{print $2}')
POUT=$(tail -1 "postProcessing/pOut/$(latest pOut)/surfaceFieldValue.dat" | awk '{print $2}')
grep -E "SIMPLE solution converged|end time" log.simpleFoam | tail -1 || true
awk -v a="$PIN" -v b="$POUT" -v r="__RHO__" 'BEGIN{
    printf "ΔP_CFD  = %.3f Pa  (kinematic %.4f m2/s2 x rho %.4f)\n", (a-b)*r, a-b, r}'
echo "ΔP_core(해석해, Fluent 와 동일 상관식) = __DPREF__ Pa — CFD 는 덕트·관 항력만큼 이보다 커야 함"
"""
    allrun = allrun.replace("__RHO__", f"{rho:.4f}")
    allrun = allrun.replace("__DPREF__", f"{pf['dp_core_Pa']:.3f}")
    ar = case / "Allrun.solve"
    ar.write_text(allrun, encoding="utf-8", newline="\n")
    ar.chmod(0o755)
    return {k: pf[k] for k in ("d", "f", "dp_core_Pa", "nu", "rho", "U_face")}
